//user to create account or login on website

import userModel from "../models/userModel.js";
import validator from 'validator';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';

const createToken = (id, role = 'user') =>{
    return jwt.sign({id, role}, process.env.JWT_SECRET);
}
//Route for user login
const loginUser = async (req, res) => {
    try {
        const {email, password} = req.body;
        const user = await userModel.findOne({email});

        if(!user){
            return  res.json({success:false, message:"User does not exist"});
        }
        //user.password is hashed password stored in DB, password is plain text password from login form
        const isMatch = await bcrypt.compare(password, user.password);
        if (isMatch) {
            const token = createToken(user._id, user.role)
            res.json({success:true, token, role: user.role});
        }else{
            res.json({success:false, message:"Incorrect password"});
        }

    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}

//Route for user registration
const registerUser = async (req, res) => {
    try {
        const {name, email, password} = req.body;
        //checking user existence
        const exists = await userModel.findOne({email});

        if(exists){
            return res.json({success:false, message:"User already exists"});
        }

        //validating email format & strong password
        if (!validator.isEmail(email) ) {
            return res.json({success:false, message:"Please enter a valid email"});
        }
        
        // Validar contraseña: mínimo 6 caracteres, letras y números
        const passwordRegex = /^(?=.*[a-zA-Z])(?=.*\d).{6,}$/;
        if (!passwordRegex.test(password)) {
            return res.json({success:false, message:"La contraseña debe tener al menos 6 caracteres, incluyendo letras y números"});
        }
        //hash password before saving to DB
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);

        const newUser = new userModel({
            name,
            email,
            password: hashedPassword,
            role: 'user'
        })

        const user = await newUser.save();
        
        const token = createToken(user._id, 'user')//_id generated by mongoDB 

        res.json({success:true, token, role: 'user'});

    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}

//Route for admin login
const loginAdmin = async (req, res) => {
   try {
        const {email, password} = req.body;
        
        // Buscar usuario admin en la base de datos
        const admin = await userModel.findOne({email});
        
        if (!admin) {
            return res.json({success:false, message:"Admin not found"});
        }
        
        if (admin.role !== 'admin') {
            return res.json({success:false, message:"Access denied: Not an admin user"});
        }
        
        // Comparar contraseña con hash
        const isMatch = await bcrypt.compare(password, admin.password);
        if (isMatch) {
            const token = createToken(admin._id, 'admin');
            res.json({success:true, token, role: 'admin'});
        } else {
            res.json({success:false, message:"Incorrect password"});
        }
   } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
   }
}

// ========== CRUD DE USUARIOS ==========

// Listar todos los usuarios (GET)
const listUsers = async (req, res) => {
    try {
        const users = await userModel.find({}).select('-password'); // No enviar contraseñas
        res.json({success:true, users});
    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}

// Obtener un usuario específico (GET)
const getUser = async (req, res) => {
    try {
        const { id } = req.params;
        const user = await userModel.findById(id).select('-password');
        
        if (!user) {
            return res.json({success:false, message:"User not found"});
        }
        
        res.json({success:true, user});
    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}

// Actualizar usuario completamente (PUT)
const updateUser = async (req, res) => {
    try {
        const { id } = req.params;
        const {name, email, password} = req.body;
        
        const user = await userModel.findById(id);
        if (!user) {
            return res.json({success:false, message:"User not found"});
        }

        // Validar email si se proporciona
        if (email && !validator.isEmail(email)) {
            return res.json({success:false, message:"Please enter a valid email"});
        }

        // Si se actualiza la contraseña, hashearla
        let updateData = { name, email };
        if (password) {
            // Validar contraseña: mínimo 6 caracteres, letras y números
            const passwordRegex = /^(?=.*[a-zA-Z])(?=.*\d).{6,}$/;
            if (!passwordRegex.test(password)) {
                return res.json({success:false, message:"Password must have at least 6 characters, including letters and numbers"});
            }
            const salt = await bcrypt.genSalt(10);
            const hashedPassword = await bcrypt.hash(password, salt);
            updateData.password = hashedPassword;
        }

        await userModel.findByIdAndUpdate(id, updateData);
        res.json({success:true, message:"User updated successfully"});
    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}

// Actualizar usuario parcialmente (PATCH)
const patchUser = async (req, res) => {
    try {
        const { id } = req.params;
        
        const user = await userModel.findById(id);
        if (!user) {
            return res.json({success:false, message:"User not found"});
        }

        const updateData = {};
        
        if (req.body.name) updateData.name = req.body.name;
        
        if (req.body.email) {
            if (!validator.isEmail(req.body.email)) {
                return res.json({success:false, message:"Please enter a valid email"});
            }
            updateData.email = req.body.email;
        }
        
        if (req.body.password) {
            // Validar contraseña: mínimo 6 caracteres, letras y números
            const passwordRegex = /^(?=.*[a-zA-Z])(?=.*\d).{6,}$/;
            if (!passwordRegex.test(req.body.password)) {
                return res.json({success:false, message:"Password must have at least 6 characters, including letters and numbers"});
            }
            const salt = await bcrypt.genSalt(10);
            const hashedPassword = await bcrypt.hash(req.body.password, salt);
            updateData.password = hashedPassword;
        }

        if (req.body.favData) updateData.favData = req.body.favData;

        await userModel.findByIdAndUpdate(id, updateData);
        res.json({success:true, message:"User partially updated successfully"});
    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}

// Eliminar usuario (DELETE)
const deleteUser = async (req, res) => {
    try {
        const { id } = req.params;
        await userModel.findByIdAndDelete(id);
        res.json({success:true, message:"User deleted successfully"});
    } catch (error) {
        console.log(error);
        res.json({success:false, message:error.message});
    }
}


export { loginUser, registerUser, loginAdmin, listUsers, getUser, updateUser, patchUser, deleteUser };